name: PR Notifications

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add comment to PR
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          :warning: There seems to be an issue with your pull request. Please check the details.
        token: ${{ secrets.pat_token }}

    - name: Send PR message
      run: |
        PR_URL="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
        MESSAGE="A new pull request has been opened or updated: $PR_URL"
        echo "Sending message to the PR..."
        echo "$MESSAGE"
