name: custom legal scan
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch:

jobs:
  code_checkout:
    name: stage1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run action
        uses: https://github.com/OSrivalli/Legal_check/main@main
        with:
          token: ${{ secrets.PAT_TOKEN }}
